---
# Editor module
# Emacs with Prelude configuration and tools

# Editor dependencies
homebrew_packages:
  - emacs
  - vim
  - neovim

# Stow directories for editor configs
stow_dirs:
  - editor

# Files that should be merged with other modules
mergeable_files:
  - ".zshrc"      # Editor aliases and functions
  - ".zshenv"     # Editor environment variables

# Note: This module provides:
# - Emacs with Prelude framework
# - Complete Emacs configuration from legacy setup
# - Editor environment variables
# - Editor productivity functions and scripts
# - TypeScript, LSP, and web development support
# - Custom themes and key bindings
