---
# ChatGPT module
# OpenAI ChatGPT desktop application

# ChatGPT from Homebrew Cask (Apple Silicon)
homebrew_casks:
  - chatgpt

# Stow directories for ChatGPT configs
stow_dirs:
  - chatgpt

# Note: This module provides:
# - ChatGPT desktop application for AI conversations
# - Configuration files for ChatGPT settings
# - Integration with other productivity tools
# - AI-powered assistance workflows
