---
# ChatGPT module
# OpenAI ChatGPT desktop application

# Note: ChatGPT desktop app is only available for ARM64 (Apple Silicon) Macs
# For Intel Macs, use the web version at https://chat.openai.com/
# or install via direct download from OpenAI

# Stow directories for ChatGPT configs
stow_dirs:
  - chatgpt

# Note: This module provides:
# - ChatGPT configuration files and documentation
# - Integration with other productivity tools
# - AI-powered assistance workflows
# - Instructions for accessing ChatGPT on Intel Macs
